apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: radius
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::817312594854:role/my-role

