name: Applications.Dapr
location:
  global:
    "http://applications-rp.radius-system:5443"
types:
  configurationStores:
    apiVersions:
      "2023-10-01-preview":
        schema: {}
    capabilities: []
  pubSubBrokers:
    apiVersions:
      "2023-10-01-preview":
        schema: {}
    capabilities: []
  secretStores:
    apiVersions:
      "2023-10-01-preview":
        schema: {}
    capabilities: []
  stateStores:
    apiVersions:
      "2023-10-01-preview":
        schema: {}
    capabilities: []
  