# ------------------------------------------------------------
# Copyright 2023 The Radius Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------

name: Purge test resources

permissions:
  id-token: write # Required for requesting the JWT
  contents: read # Required for actions/checkout
  packages: write # Required for reading package versions and deleting packages

on:
  # Enable manual trigger
  workflow_dispatch:
  schedule:
    # Run twice a day
    - cron: "30 0,12 * * *"

env:
  AZURE_RG_DELETE_LIST_FILE: "az_rg_list.txt"
  # The valid resource time window in seconds to delete the test resources. 6 hours
  VALID_RESOURCE_WINDOW: 6*60*60
  # The current GitHub action link
  ACTION_LINK: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  purge_ghcr_dev:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout
      packages: all # Required for reading package versions and deleting packages
    if: github.repository == 'radius-project/radius'
    steps:
      - name: Delete 'dev' containers older than a week
        uses: snok/container-retention-policy@v2
        with:
          image-names: dev/*
          cut-off: 3 days ago UTC
          account-type: org
          org-name: radius-project
          token: ${{ secrets.GH_RAD_CI_BOT_PAT }}
          keep-at-least: 1

  